#!/bin/bash
 #	This script will search and replace all regular files for a string 
 #	supplied by the user and replace it with another string. 
 #	
 #	Written by Josef Nevoral
 #	josef.nevoral@gmail.com
 #

 ########## FUNCTIONS ####################
 function usage {
   echo "Not enough parameters provided."
   echo "Usage: ./$0 searchstring replacestring"
   echo "Remember to escape any special characters in the searchstring or the replacestring"
   echo ""
 }

 function help {
  echo "####### Help to searchReplace script #######"
  echo "Options:"
  echo "	-m or --mask: regular expression for filename to search"
  echo "	-p or --path: path to directory in which to search for files"
  echo "	-b or --backup: create backup of changed files with timestamp"
  echo "	-d or --dirmask: specify directory mask in which should files be"
  echo "	-h or --help: this help obviously :-)"
  echo ""
  echo "Parameters:"
  echo "	searchstring: string to search for - dont forget to escape special characters"
  echo "	replacestring: string to replace by - dont forget to escape special characters"
 }
 ########## END FUNCTIONS ################

 mask=
 dirmask=
 path='.'
 createBackup=false

 while [ "$#" != 0 ];
 do
  case "$1" in
	-m | --mask)
		mask=$2
		shift 2;;
	-p | --path)
		path=$2
		shift 2;;
	-b | --backup)
		createBackup=true
		shift;;
	-h | --help) 
		help 
		shift;;
	-d | --dirmast)
		dirmask=$2
		shift 2;;
	*)
	  break
  esac
 done
 #check for required parameters
 if  [ ${#1} -gt 0  ]  &&  [ ${#2} -gt 0  ];
 then
  findCommand="find $path -type f"
  if [ $mask ];
  then
    findCommand="$findCommand -name $mask"
  fi
  for file in `$findCommand`;
  do
   if grep -q $1 $file;
   then
    dirpath=$(dirname $(readlink -f "$file"))
    dir=${dirpath##/*/}
    compare=$(echo $dir | grep $dirmask)
    if [ ! $(echo $dir | grep "$dirmask") ] 
    then
      continue
    fi
    cp $file $file.bak
    echo "The string $1 will be replaced with $2 in $file"
    sed "s/$1/$2/g" "$file.bak" > $file
    if [ $createBackup == false ]
    then
      rm $file.bak
    fi
   fi
  done
 else
  #print usage information 
  usage
 fi
